<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'totals' => array( 'sol_id' => array( 'totalsType' => '' ),
'ID_FK' => array( 'totalsType' => '' ),
'sol_ticket' => array( 'totalsType' => '' ),
'nombre' => array( 'totalsType' => '' ),
'primer_apellido' => array( 'totalsType' => '' ),
'segundo_apellido' => array( 'totalsType' => '' ),
'tipo_documento' => array( 'totalsType' => '' ),
'numero_documento' => array( 'totalsType' => '' ),
'telefono' => array( 'totalsType' => '' ),
'departamento' => array( 'totalsType' => '' ),
'municipio' => array( 'totalsType' => '' ),
'direccion' => array( 'totalsType' => '' ),
'cargo' => array( 'totalsType' => '' ),
'email_contacto' => array( 'totalsType' => '' ),
'email_contacto_c' => array( 'totalsType' => '' ),
'token_id' => array( 'totalsType' => '' ),
'cert_id' => array( 'totalsType' => '' ),
'vigencia' => array( 'totalsType' => '' ),
'stage' => array( 'totalsType' => '' ),
'stage_tk' => array( 'totalsType' => '' ),
'doc_acta' => array( 'totalsType' => '' ),
'doc_carta' => array( 'totalsType' => '' ),
'doc_certificado' => array( 'totalsType' => '' ),
'doc_poder' => array( 'totalsType' => '' ),
'doc_rut' => array( 'totalsType' => '' ),
'doc_cedula' => array( 'totalsType' => '' ),
'doc_escritura' => array( 'totalsType' => '' ),
'tk_fecha_i' => array( 'totalsType' => '' ),
'tl_fecha_f' => array( 'totalsType' => '' ),
'dep' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'sol_id',
'sol_ticket',
'ID_FK',
'nombre',
'primer_apellido',
'segundo_apellido',
'tipo_documento',
'numero_documento',
'telefono',
'departamento',
'municipio',
'direccion',
'cargo',
'email_contacto',
'email_contacto_c',
'token_id',
'cert_id',
'vigencia',
'stage',
'doc_acta',
'doc_carta',
'doc_certificado',
'doc_poder',
'doc_rut',
'doc_cedula',
'doc_escritura',
'stage_tk',
'tl_fecha_f',
'dep' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'sol_id' => array( 'simple_grid_field',
'simple_grid_field29' ),
'sol_ticket' => array( 'simple_grid_field1',
'simple_grid_field47' ),
'ID_FK' => array( 'simple_grid_field2',
'simple_grid_field30' ),
'nombre' => array( 'simple_grid_field3',
'simple_grid_field31' ),
'primer_apellido' => array( 'simple_grid_field4',
'simple_grid_field32' ),
'segundo_apellido' => array( 'simple_grid_field5',
'simple_grid_field33' ),
'tipo_documento' => array( 'simple_grid_field6',
'simple_grid_field34' ),
'numero_documento' => array( 'simple_grid_field7',
'simple_grid_field35' ),
'telefono' => array( 'simple_grid_field8',
'simple_grid_field36' ),
'departamento' => array( 'simple_grid_field9',
'simple_grid_field37' ),
'municipio' => array( 'simple_grid_field10',
'simple_grid_field38' ),
'direccion' => array( 'simple_grid_field11',
'simple_grid_field39' ),
'cargo' => array( 'simple_grid_field12',
'simple_grid_field40' ),
'email_contacto' => array( 'simple_grid_field13',
'simple_grid_field41' ),
'email_contacto_c' => array( 'simple_grid_field14',
'simple_grid_field42' ),
'token_id' => array( 'simple_grid_field15',
'simple_grid_field43' ),
'cert_id' => array( 'simple_grid_field16',
'simple_grid_field44' ),
'vigencia' => array( 'simple_grid_field17',
'simple_grid_field45' ),
'stage' => array( 'simple_grid_field18',
'simple_grid_field46' ),
'doc_acta' => array( 'simple_grid_field19',
'simple_grid_field48' ),
'doc_carta' => array( 'simple_grid_field20',
'simple_grid_field49' ),
'doc_certificado' => array( 'simple_grid_field21',
'simple_grid_field50' ),
'doc_poder' => array( 'simple_grid_field22',
'simple_grid_field51' ),
'doc_rut' => array( 'simple_grid_field23',
'simple_grid_field52' ),
'doc_cedula' => array( 'simple_grid_field24',
'simple_grid_field53' ),
'doc_escritura' => array( 'simple_grid_field25',
'simple_grid_field54' ),
'stage_tk' => array( 'simple_grid_field26',
'simple_grid_field56' ),
'tl_fecha_f' => array( 'simple_grid_field27',
'simple_grid_field55' ),
'dep' => array( 'simple_grid_field28',
'simple_grid_field57' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'print_header',
'print_subheader' ),
'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'grid' => array( 'simple_grid_field29',
'simple_grid_field',
'simple_grid_field39',
'simple_grid_field11',
'simple_grid_field49',
'simple_grid_field20',
'simple_grid_field30',
'simple_grid_field2',
'simple_grid_field40',
'simple_grid_field12',
'simple_grid_field50',
'simple_grid_field21',
'simple_grid_field31',
'simple_grid_field3',
'simple_grid_field41',
'simple_grid_field13',
'simple_grid_field51',
'simple_grid_field22',
'simple_grid_field32',
'simple_grid_field4',
'simple_grid_field42',
'simple_grid_field14',
'simple_grid_field52',
'simple_grid_field23',
'simple_grid_field33',
'simple_grid_field5',
'simple_grid_field43',
'simple_grid_field15',
'simple_grid_field53',
'simple_grid_field24',
'simple_grid_field34',
'simple_grid_field6',
'simple_grid_field44',
'simple_grid_field16',
'simple_grid_field54',
'simple_grid_field25',
'simple_grid_field35',
'simple_grid_field7',
'simple_grid_field45',
'simple_grid_field17',
'simple_grid_field55',
'simple_grid_field27',
'simple_grid_field36',
'simple_grid_field8',
'simple_grid_field46',
'simple_grid_field18',
'simple_grid_field56',
'simple_grid_field26',
'simple_grid_field37',
'simple_grid_field9',
'simple_grid_field47',
'simple_grid_field1',
'simple_grid_field57',
'simple_grid_field28',
'simple_grid_field38',
'simple_grid_field10',
'simple_grid_field48',
'simple_grid_field19' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_header' => 'top',
'print_subheader' => 'top',
'print_pages' => 'above-grid',
'simple_grid_field29' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field49' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field50' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field51' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field52' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field53' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field54' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field56' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field57' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field48' => 'grid',
'simple_grid_field19' => 'grid' ),
'itemLocations' => array( 'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_label' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'cell_label1' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'cell_label2' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_label3' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'cell_label4' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'cell_label5' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_label6' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'cell_label7' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'cell_label8' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'cell_label9' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'cell_label10' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field52' => array( 'location' => 'grid',
'cellId' => 'cell_label11' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'cell_label12' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'cell_label13' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field53' => array( 'location' => 'grid',
'cellId' => 'cell_label14' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'cell_label15' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'cell_label16' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field54' => array( 'location' => 'grid',
'cellId' => 'cell_label17' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'cell_label18' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'cell_label19' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'cell_label20' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'cell_label21' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'cell_label22' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field56' => array( 'location' => 'grid',
'cellId' => 'cell_label23' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'cell_label24' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'cell_label25' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field57' => array( 'location' => 'grid',
'cellId' => 'cell_label26' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'cell_label27' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'simple_grid_field48' => array( 'location' => 'grid',
'cellId' => 'cell_label28' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28' ),
'grid_field_label' => array( 'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field40',
'simple_grid_field41',
'simple_grid_field42',
'simple_grid_field43',
'simple_grid_field44',
'simple_grid_field45',
'simple_grid_field46',
'simple_grid_field47',
'simple_grid_field48',
'simple_grid_field49',
'simple_grid_field50',
'simple_grid_field51',
'simple_grid_field52',
'simple_grid_field53',
'simple_grid_field54',
'simple_grid_field55',
'simple_grid_field56',
'simple_grid_field57' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0,
1,
2,
3,
4,
5 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'sol_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'sol_id_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label1' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'direccion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'direccion_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label2' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'doc_carta_fieldheadercolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'doc_carta_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label3' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'ID_FK_fieldheadercolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array( 'ID_FK_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label4' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array( 'cargo_fieldheadercolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array( 'cargo_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label5' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array( 'doc_certificado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array( 'doc_certificado_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label6' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'nombre_fieldheadercolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array( 'nombre_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label7' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array( 'email_contacto_fieldheadercolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array( 'email_contacto_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label8' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array( 'doc_poder_fieldheadercolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array( 'doc_poder_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label9' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'primer_apellido_fieldheadercolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array( 'primer_apellido_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label10' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array( 'email_contacto_c_fieldheadercolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array( 'email_contacto_c_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label11' => array( 'cols' => array( 4 ),
'rows' => array( 4 ),
'tags' => array( 'doc_rut_fieldheadercolumn' ),
'items' => array( 'simple_grid_field52' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 5 ),
'rows' => array( 4 ),
'tags' => array( 'doc_rut_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label12' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'segundo_apellido_fieldheadercolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array( 'segundo_apellido_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label13' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array( 'token_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 3 ),
'rows' => array( 5 ),
'tags' => array( 'token_id_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label14' => array( 'cols' => array( 4 ),
'rows' => array( 5 ),
'tags' => array( 'doc_cedula_fieldheadercolumn' ),
'items' => array( 'simple_grid_field53' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 5 ),
'rows' => array( 5 ),
'tags' => array( 'doc_cedula_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label15' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array( 'tipo_documento_fieldheadercolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array( 'tipo_documento_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label16' => array( 'cols' => array( 2 ),
'rows' => array( 6 ),
'tags' => array( 'cert_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 3 ),
'rows' => array( 6 ),
'tags' => array( 'cert_id_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label17' => array( 'cols' => array( 4 ),
'rows' => array( 6 ),
'tags' => array( 'doc_escritura_fieldheadercolumn' ),
'items' => array( 'simple_grid_field54' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 5 ),
'rows' => array( 6 ),
'tags' => array( 'doc_escritura_fieldcolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label18' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array( 'numero_documento_fieldheadercolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array( 'numero_documento_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label19' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array( 'vigencia_fieldheadercolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 3 ),
'rows' => array( 7 ),
'tags' => array( 'vigencia_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label20' => array( 'cols' => array( 4 ),
'rows' => array( 7 ),
'tags' => array( 'tl_fecha_f_fieldheadercolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 5 ),
'rows' => array( 7 ),
'tags' => array( 'tl_fecha_f_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label21' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array( 'telefono_fieldheadercolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 1 ),
'rows' => array( 8 ),
'tags' => array( 'telefono_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label22' => array( 'cols' => array( 2 ),
'rows' => array( 8 ),
'tags' => array( 'stage_fieldheadercolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 3 ),
'rows' => array( 8 ),
'tags' => array( 'stage_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label23' => array( 'cols' => array( 4 ),
'rows' => array( 8 ),
'tags' => array( 'stage_tk_fieldheadercolumn' ),
'items' => array( 'simple_grid_field56' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 5 ),
'rows' => array( 8 ),
'tags' => array( 'stage_tk_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label24' => array( 'cols' => array( 0 ),
'rows' => array( 9 ),
'tags' => array( 'departamento_fieldheadercolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 1 ),
'rows' => array( 9 ),
'tags' => array( 'departamento_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label25' => array( 'cols' => array( 2 ),
'rows' => array( 9 ),
'tags' => array( 'sol_ticket_fieldheadercolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 3 ),
'rows' => array( 9 ),
'tags' => array( 'sol_ticket_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label26' => array( 'cols' => array( 4 ),
'rows' => array( 9 ),
'tags' => array( 'dep_fieldheadercolumn' ),
'items' => array( 'simple_grid_field57' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 5 ),
'rows' => array( 9 ),
'tags' => array( 'dep_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label27' => array( 'cols' => array( 0 ),
'rows' => array( 10 ),
'tags' => array( 'municipio_fieldheadercolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 1 ),
'rows' => array( 10 ),
'tags' => array( 'municipio_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label28' => array( 'cols' => array( 2 ),
'rows' => array( 10 ),
'tags' => array( 'doc_acta_fieldheadercolumn' ),
'items' => array( 'simple_grid_field48' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 3 ),
'rows' => array( 10 ),
'tags' => array( 'doc_acta_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label29' => array( 'cols' => array( 4 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 5 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3,
4,
5 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 6,
'height' => 12 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 2,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'columns-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 6 ) ),
'section' => 'head' ),
array( 'cells' => array( array( 'cell' => 'cell_label' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_label1' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_label2' ),
array( 'cell' => 'cell_field2' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label3' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_label4' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_label5' ),
array( 'cell' => 'cell_field5' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label6' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_label7' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_label8' ),
array( 'cell' => 'cell_field8' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label9' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_label10' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_label11' ),
array( 'cell' => 'cell_field11' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label12' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_label13' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_label14' ),
array( 'cell' => 'cell_field14' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label15' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_label16' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_label17' ),
array( 'cell' => 'cell_field17' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label18' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_label19' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_label20' ),
array( 'cell' => 'cell_field20' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label21' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_label22' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_label23' ),
array( 'cell' => 'cell_field23' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label24' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_label25' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_label26' ),
array( 'cell' => 'cell_field26' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label27' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_label28' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_label29' ),
array( 'cell' => 'cell_field29' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 6 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_top' => array( 'model' => 'cell_top',
'items' => array(  ) ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array(  ) ),
'cell_label' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field29' ),
'field' => 'sol_id',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'sol_id',
'columnName' => 'field' ),
'cell_label1' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field39' ),
'field' => 'direccion',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'direccion',
'columnName' => 'field' ),
'cell_label2' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field49' ),
'field' => 'doc_carta',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'doc_carta',
'columnName' => 'field' ),
'cell_label3' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field30' ),
'field' => 'ID_FK',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'ID_FK',
'columnName' => 'field' ),
'cell_label4' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field40' ),
'field' => 'cargo',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'cargo',
'columnName' => 'field' ),
'cell_label5' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field50' ),
'field' => 'doc_certificado',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'doc_certificado',
'columnName' => 'field' ),
'cell_label6' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field31' ),
'field' => 'nombre',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'nombre',
'columnName' => 'field' ),
'cell_label7' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field41' ),
'field' => 'email_contacto',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'email_contacto',
'columnName' => 'field' ),
'cell_label8' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field51' ),
'field' => 'doc_poder',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'doc_poder',
'columnName' => 'field' ),
'cell_label9' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field32' ),
'field' => 'primer_apellido',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'primer_apellido',
'columnName' => 'field' ),
'cell_label10' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field42' ),
'field' => 'email_contacto_c',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'email_contacto_c',
'columnName' => 'field' ),
'cell_label11' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field52' ),
'field' => 'doc_rut',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'doc_rut',
'columnName' => 'field' ),
'cell_label12' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field33' ),
'field' => 'segundo_apellido',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'segundo_apellido',
'columnName' => 'field' ),
'cell_label13' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field43' ),
'field' => 'token_id',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'token_id',
'columnName' => 'field' ),
'cell_label14' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field53' ),
'field' => 'doc_cedula',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'doc_cedula',
'columnName' => 'field' ),
'cell_label15' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field34' ),
'field' => 'tipo_documento',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'tipo_documento',
'columnName' => 'field' ),
'cell_label16' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field44' ),
'field' => 'cert_id',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'cert_id',
'columnName' => 'field' ),
'cell_label17' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field54' ),
'field' => 'doc_escritura',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'doc_escritura',
'columnName' => 'field' ),
'cell_label18' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field35' ),
'field' => 'numero_documento',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'numero_documento',
'columnName' => 'field' ),
'cell_label19' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field45' ),
'field' => 'vigencia',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'vigencia',
'columnName' => 'field' ),
'cell_label20' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field55' ),
'field' => 'tl_fecha_f',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'tl_fecha_f',
'columnName' => 'field' ),
'cell_label21' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field36' ),
'field' => 'telefono',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'telefono',
'columnName' => 'field' ),
'cell_label22' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field46' ),
'field' => 'stage',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'stage',
'columnName' => 'field' ),
'cell_label23' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field56' ),
'field' => 'stage_tk',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'stage_tk',
'columnName' => 'field' ),
'cell_label24' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field37' ),
'field' => 'departamento',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'departamento',
'columnName' => 'field' ),
'cell_label25' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field47' ),
'field' => 'sol_ticket',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'sol_ticket',
'columnName' => 'field' ),
'cell_label26' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field57' ),
'field' => 'dep',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'dep',
'columnName' => 'field' ),
'cell_label27' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field38' ),
'field' => 'municipio',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'municipio',
'columnName' => 'field' ),
'cell_label28' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field48' ),
'field' => 'doc_acta',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'doc_acta',
'columnName' => 'field' ),
'cell_label29' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'buildType' => 2,
'columnCount' => 3 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'simple_grid_field' => array( 'field' => 'sol_id',
'type' => 'grid_field' ),
'simple_grid_field1' => array( 'field' => 'sol_ticket',
'type' => 'grid_field' ),
'simple_grid_field2' => array( 'field' => 'ID_FK',
'type' => 'grid_field' ),
'simple_grid_field3' => array( 'field' => 'nombre',
'type' => 'grid_field' ),
'simple_grid_field4' => array( 'field' => 'primer_apellido',
'type' => 'grid_field' ),
'simple_grid_field5' => array( 'field' => 'segundo_apellido',
'type' => 'grid_field' ),
'simple_grid_field6' => array( 'field' => 'tipo_documento',
'type' => 'grid_field' ),
'simple_grid_field7' => array( 'field' => 'numero_documento',
'type' => 'grid_field' ),
'simple_grid_field8' => array( 'field' => 'telefono',
'type' => 'grid_field' ),
'simple_grid_field9' => array( 'field' => 'departamento',
'type' => 'grid_field' ),
'simple_grid_field10' => array( 'field' => 'municipio',
'type' => 'grid_field' ),
'simple_grid_field11' => array( 'field' => 'direccion',
'type' => 'grid_field' ),
'simple_grid_field12' => array( 'field' => 'cargo',
'type' => 'grid_field' ),
'simple_grid_field13' => array( 'field' => 'email_contacto',
'type' => 'grid_field' ),
'simple_grid_field14' => array( 'field' => 'email_contacto_c',
'type' => 'grid_field' ),
'simple_grid_field15' => array( 'field' => 'token_id',
'type' => 'grid_field' ),
'simple_grid_field16' => array( 'field' => 'cert_id',
'type' => 'grid_field' ),
'simple_grid_field17' => array( 'field' => 'vigencia',
'type' => 'grid_field' ),
'simple_grid_field18' => array( 'field' => 'stage',
'type' => 'grid_field' ),
'simple_grid_field19' => array( 'field' => 'doc_acta',
'type' => 'grid_field' ),
'simple_grid_field20' => array( 'field' => 'doc_carta',
'type' => 'grid_field' ),
'simple_grid_field21' => array( 'field' => 'doc_certificado',
'type' => 'grid_field' ),
'simple_grid_field22' => array( 'field' => 'doc_poder',
'type' => 'grid_field' ),
'simple_grid_field23' => array( 'field' => 'doc_rut',
'type' => 'grid_field' ),
'simple_grid_field24' => array( 'field' => 'doc_cedula',
'type' => 'grid_field' ),
'simple_grid_field25' => array( 'field' => 'doc_escritura',
'type' => 'grid_field' ),
'simple_grid_field26' => array( 'field' => 'stage_tk',
'type' => 'grid_field' ),
'simple_grid_field27' => array( 'field' => 'tl_fecha_f',
'type' => 'grid_field' ),
'simple_grid_field28' => array( 'field' => 'dep',
'type' => 'grid_field' ),
'simple_grid_field29' => array( 'type' => 'grid_field_label',
'field' => 'sol_id' ),
'simple_grid_field30' => array( 'type' => 'grid_field_label',
'field' => 'ID_FK' ),
'simple_grid_field31' => array( 'type' => 'grid_field_label',
'field' => 'nombre' ),
'simple_grid_field32' => array( 'type' => 'grid_field_label',
'field' => 'primer_apellido' ),
'simple_grid_field33' => array( 'type' => 'grid_field_label',
'field' => 'segundo_apellido' ),
'simple_grid_field34' => array( 'type' => 'grid_field_label',
'field' => 'tipo_documento' ),
'simple_grid_field35' => array( 'type' => 'grid_field_label',
'field' => 'numero_documento' ),
'simple_grid_field36' => array( 'type' => 'grid_field_label',
'field' => 'telefono' ),
'simple_grid_field37' => array( 'type' => 'grid_field_label',
'field' => 'departamento' ),
'simple_grid_field38' => array( 'type' => 'grid_field_label',
'field' => 'municipio' ),
'simple_grid_field39' => array( 'type' => 'grid_field_label',
'field' => 'direccion' ),
'simple_grid_field40' => array( 'type' => 'grid_field_label',
'field' => 'cargo' ),
'simple_grid_field41' => array( 'type' => 'grid_field_label',
'field' => 'email_contacto' ),
'simple_grid_field42' => array( 'type' => 'grid_field_label',
'field' => 'email_contacto_c' ),
'simple_grid_field43' => array( 'type' => 'grid_field_label',
'field' => 'token_id' ),
'simple_grid_field44' => array( 'type' => 'grid_field_label',
'field' => 'cert_id' ),
'simple_grid_field45' => array( 'type' => 'grid_field_label',
'field' => 'vigencia' ),
'simple_grid_field46' => array( 'type' => 'grid_field_label',
'field' => 'stage' ),
'simple_grid_field47' => array( 'type' => 'grid_field_label',
'field' => 'sol_ticket' ),
'simple_grid_field48' => array( 'type' => 'grid_field_label',
'field' => 'doc_acta' ),
'simple_grid_field49' => array( 'type' => 'grid_field_label',
'field' => 'doc_carta' ),
'simple_grid_field50' => array( 'type' => 'grid_field_label',
'field' => 'doc_certificado' ),
'simple_grid_field51' => array( 'type' => 'grid_field_label',
'field' => 'doc_poder' ),
'simple_grid_field52' => array( 'type' => 'grid_field_label',
'field' => 'doc_rut' ),
'simple_grid_field53' => array( 'type' => 'grid_field_label',
'field' => 'doc_cedula' ),
'simple_grid_field54' => array( 'type' => 'grid_field_label',
'field' => 'doc_escritura' ),
'simple_grid_field55' => array( 'type' => 'grid_field_label',
'field' => 'tl_fecha_f' ),
'simple_grid_field56' => array( 'type' => 'grid_field_label',
'field' => 'stage_tk' ),
'simple_grid_field57' => array( 'type' => 'grid_field_label',
'field' => 'dep' ) ),
'dbProps' => array(  ),
'version' => 13,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>