<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => true,
'orientation' => 'portrait',
'scale' => 100 ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'fields' => array( 'gridFields' => array( 'stage_tk',
'vigencia',
'cert_id',
'token_id',
'email_contacto',
'cargo',
'direccion',
'municipio',
'departamento',
'telefono',
'numero_documento',
'tipo_documento',
'segundo_apellido',
'primer_apellido',
'nombre',
'sol_id',
'tl_fecha_f',
'dep' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'ID_FK',
'dep',
'tl_fecha_f',
'vigencia',
'token_id',
'tipo_documento',
'telefono',
'stage_tk',
'stage',
'sol_id',
'segundo_apellido',
'primer_apellido',
'numero_documento',
'nombre',
'municipio',
'email_contacto',
'direccion',
'departamento',
'cert_id',
'cargo' ),
'filterFields' => array( 'departamento',
'tl_fecha_f',
'municipio',
'cert_id',
'token_id' ),
'fieldItems' => array( 'stage_tk' => array( 'report_grid_field19' ),
'stage' => array( 'report_group_field1' ),
'vigencia' => array( 'report_grid_field17' ),
'cert_id' => array( 'report_grid_field16' ),
'token_id' => array( 'report_grid_field15' ),
'email_contacto' => array( 'report_grid_field13' ),
'cargo' => array( 'report_grid_field12' ),
'direccion' => array( 'report_grid_field11' ),
'municipio' => array( 'report_grid_field10' ),
'departamento' => array( 'report_grid_field9' ),
'telefono' => array( 'report_grid_field8' ),
'numero_documento' => array( 'report_grid_field7' ),
'tipo_documento' => array( 'report_grid_field6' ),
'segundo_apellido' => array( 'report_grid_field5' ),
'primer_apellido' => array( 'report_grid_field4' ),
'nombre' => array( 'report_grid_field3' ),
'ID_FK' => array( 'report_group_field' ),
'sol_id' => array( 'report_grid_field' ),
'tl_fecha_f' => array( 'report_grid_field1' ),
'dep' => array( 'report_grid_field2' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel',
'filter_panel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'grid' => array( 'report_group_field',
'report_group_field1',
'report_grid_field',
'report_grid_field3',
'report_grid_field4',
'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field9',
'report_grid_field10',
'report_grid_field11',
'report_grid_field12',
'report_grid_field13',
'report_grid_field15',
'report_grid_field16',
'report_grid_field17',
'report_grid_field19',
'report_grid_field1',
'report_grid_field2' ),
'top' => array(  ),
'above-grid' => array( 'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ) ),
'formXtTags' => array( 'top' => array(  ),
'above-grid' => array( 'details_found',
'grpsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'filter_panel' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'report_group_field' => 'grid',
'report_group_field1' => 'grid',
'report_grid_field' => 'grid',
'report_grid_field3' => 'grid',
'report_grid_field4' => 'grid',
'report_grid_field5' => 'grid',
'report_grid_field6' => 'grid',
'report_grid_field7' => 'grid',
'report_grid_field8' => 'grid',
'report_grid_field9' => 'grid',
'report_grid_field10' => 'grid',
'report_grid_field11' => 'grid',
'report_grid_field12' => 'grid',
'report_grid_field13' => 'grid',
'report_grid_field15' => 'grid',
'report_grid_field16' => 'grid',
'report_grid_field17' => 'grid',
'report_grid_field19' => 'grid',
'report_grid_field1' => 'grid',
'report_grid_field2' => 'grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'print_panel' => 5,
'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'export_report_excel' => array( 'export_report_excel' ),
'export_report_word' => array( 'export_report_word' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'-' => array( '-',
'-1' ),
'search_panel' => array( 'search_panel' ),
'report_grid_field' => array( 'report_grid_field19',
'report_grid_field17',
'report_grid_field16',
'report_grid_field15',
'report_grid_field13',
'report_grid_field12',
'report_grid_field11',
'report_grid_field10',
'report_grid_field9',
'report_grid_field8',
'report_grid_field7',
'report_grid_field6',
'report_grid_field5',
'report_grid_field4',
'report_grid_field3',
'report_grid_field',
'report_grid_field1',
'report_grid_field2' ),
'report_group_field' => array( 'report_group_field1',
'report_group_field' ),
'filter_panel_field' => array( 'filter_panel_field',
'filter_panel_field4',
'filter_panel_field1',
'filter_panel_field2',
'filter_panel_field3' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'collapse_button' => array( 'collapse_button' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'advsearch_link' => array( 'advsearch_link' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field12',
'search_panel_field14',
'search_panel_field15',
'search_panel_field16',
'search_panel_field17',
'search_panel_field18',
'search_panel_field19',
'search_panel_field21',
'search_panel_field22',
'search_panel_field23',
'search_panel_field24',
'search_panel_field27',
'search_panel_field31',
'search_panel_field6' ),
'filter_panel' => array( 'filter_panel' ),
'export_report_pdf' => array( 'export_report_pdf' ),
'logo' => array( 'logo1' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'userinfo_link' => array( 'userinfo_link' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'report',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'newreport' => array( 'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '7ACA7A',
'summary' => '90EE90' ),
'field' => 'ID_FK' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '93B7C3',
'summary' => 'ADD8E6' ),
'field' => 'stage' ) ),
'fields' => array( array( 'field' => 'sol_id',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'nombre',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'primer_apellido',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'segundo_apellido',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'tipo_documento',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'numero_documento',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'telefono',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'departamento',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'municipio',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'direccion',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'cargo',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'email_contacto',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'token_id',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'cert_id',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'vigencia',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'stage_tk',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'tl_fecha_f',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'dep',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ) ),
'showData' => true,
'pageSummary' => true,
'globalSummary' => true,
'crosstab' => false,
'colors' => array( array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ) ),
'horizSummary' => false,
'layout' => 'align',
'vertSummary' => false ) ) );
			$pageArray = array( 'id' => 'report',
'type' => 'report',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel',
'filter_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-chart',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'report-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'report_group_field',
'report_group_field1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'report_grid_field',
'report_grid_field3',
'report_grid_field4',
'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field9',
'report_grid_field10',
'report_grid_field11',
'report_grid_field12',
'report_grid_field13',
'report_grid_field15',
'report_grid_field16',
'report_grid_field17',
'report_grid_field19',
'report_grid_field1',
'report_grid_field2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1,
'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '7ACA7A',
'summary' => '90EE90' ),
'field' => 'ID_FK' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '93B7C3',
'summary' => 'ADD8E6' ),
'field' => 'stage' ) ),
'fields' => array( array( 'field' => 'sol_id',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'nombre',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'primer_apellido',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'segundo_apellido',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'tipo_documento',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'numero_documento',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'telefono',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'departamento',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'municipio',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'direccion',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'cargo',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'email_contacto',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'token_id',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'cert_id',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'vigencia',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'stage_tk',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'tl_fecha_f',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'dep',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ) ),
'showData' => true,
'pageSummary' => true,
'globalSummary' => true,
'crosstab' => false,
'colors' => array( array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ),
array( 'header' => '',
'summary' => '' ) ),
'horizSummary' => false,
'layout' => 'align',
'vertSummary' => false ) ),
'top' => array( 'modelId' => 'list-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'report-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'report-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-1',
'export_report_excel',
'export_report_word',
'export_report_pdf' ) ),
'export_report_excel' => array( 'type' => 'export_report_excel' ),
'export_report_word' => array( 'type' => 'export_report_word' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'-' => array( 'type' => '-' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field6',
'search_panel_field5',
'search_panel_field31',
'search_panel_field27',
'search_panel_field24',
'search_panel_field23',
'search_panel_field22',
'search_panel_field21',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field12',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ) ),
'report_grid_field19' => array( 'field' => 'stage_tk',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_group_field1' => array( 'field' => 'stage',
'type' => 'report_group_field',
'axis' => 0,
'summary' => true,
'interval' => 0 ),
'report_grid_field17' => array( 'field' => 'vigencia',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field16' => array( 'field' => 'cert_id',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field15' => array( 'field' => 'token_id',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field13' => array( 'field' => 'email_contacto',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field12' => array( 'field' => 'cargo',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field11' => array( 'field' => 'direccion',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field10' => array( 'field' => 'municipio',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field9' => array( 'field' => 'departamento',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field8' => array( 'field' => 'telefono',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field7' => array( 'field' => 'numero_documento',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field6' => array( 'field' => 'tipo_documento',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field5' => array( 'field' => 'segundo_apellido',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field4' => array( 'field' => 'primer_apellido',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field3' => array( 'field' => 'nombre',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_group_field' => array( 'field' => 'ID_FK',
'type' => 'report_group_field',
'axis' => 0,
'summary' => true,
'interval' => 0 ),
'filter_panel_field' => array( 'field' => 'departamento',
'type' => 'filter_panel_field' ),
'report_grid_field' => array( 'field' => 'sol_id',
'type' => 'report_grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'-1' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'search_panel_field' => array( 'field' => 'ID_FK',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field1' => array( 'field' => 'cargo',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field2' => array( 'field' => 'cert_id',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field3' => array( 'field' => 'departamento',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field4' => array( 'field' => 'direccion',
'type' => 'search_panel_field',
'required' => false ),
'filter_panel_field4' => array( 'field' => 'tl_fecha_f',
'type' => 'filter_panel_field' ),
'report_grid_field1' => array( 'field' => 'tl_fecha_f',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'search_panel_field5' => array( 'field' => 'tl_fecha_f',
'type' => 'search_panel_field' ),
'search_panel_field12' => array( 'field' => 'email_contacto',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field14' => array( 'field' => 'municipio',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field15' => array( 'field' => 'nombre',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field16' => array( 'field' => 'numero_documento',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field17' => array( 'field' => 'primer_apellido',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field18' => array( 'field' => 'segundo_apellido',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field19' => array( 'field' => 'sol_id',
'type' => 'search_panel_field',
'required' => false ),
'filter_panel' => array( 'type' => 'filter_panel',
'items' => array( 'filter_panel_field',
'filter_panel_field4',
'filter_panel_field3',
'filter_panel_field2',
'filter_panel_field1' ) ),
'search_panel_field21' => array( 'field' => 'stage',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field22' => array( 'field' => 'stage_tk',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field23' => array( 'field' => 'telefono',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field24' => array( 'field' => 'tipo_documento',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field27' => array( 'field' => 'token_id',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field31' => array( 'field' => 'vigencia',
'type' => 'search_panel_field',
'required' => false ),
'export_report_pdf' => array( 'type' => 'export_report_pdf',
'targetPages' => array(  ),
'splitModes' => array(  ),
'scopes' => array(  ) ),
'filter_panel_field1' => array( 'field' => 'municipio',
'type' => 'filter_panel_field' ),
'filter_panel_field2' => array( 'field' => 'cert_id',
'type' => 'filter_panel_field' ),
'filter_panel_field3' => array( 'field' => 'token_id',
'type' => 'filter_panel_field' ),
'logo1' => array( 'type' => 'logo' ),
'report_grid_field2' => array( 'field' => 'dep',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'search_panel_field6' => array( 'field' => 'dep',
'type' => 'search_panel_field',
'required' => false ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 13,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>