<?php
			$optionsArray = array( 'totals' => array( 'sol_id' => array( 'totalsType' => '' ),
'ID_FK' => array( 'totalsType' => '' ),
'sol_ticket' => array( 'totalsType' => '' ),
'nombre' => array( 'totalsType' => '' ),
'primer_apellido' => array( 'totalsType' => '' ),
'segundo_apellido' => array( 'totalsType' => '' ),
'tipo_documento' => array( 'totalsType' => '' ),
'numero_documento' => array( 'totalsType' => '' ),
'telefono' => array( 'totalsType' => '' ),
'departamento' => array( 'totalsType' => '' ),
'municipio' => array( 'totalsType' => '' ),
'direccion' => array( 'totalsType' => '' ),
'cargo' => array( 'totalsType' => '' ),
'email_contacto' => array( 'totalsType' => '' ),
'email_contacto_c' => array( 'totalsType' => '' ),
'token_id' => array( 'totalsType' => '' ),
'cert_id' => array( 'totalsType' => '' ),
'vigencia' => array( 'totalsType' => '' ),
'stage' => array( 'totalsType' => '' ),
'stage_tk' => array( 'totalsType' => '' ),
'doc_acta' => array( 'totalsType' => '' ),
'doc_carta' => array( 'totalsType' => '' ),
'doc_certificado' => array( 'totalsType' => '' ),
'doc_poder' => array( 'totalsType' => '' ),
'doc_rut' => array( 'totalsType' => '' ),
'doc_cedula' => array( 'totalsType' => '' ),
'doc_escritura' => array( 'totalsType' => '' ),
'track_msj' => array( 'totalsType' => '' ),
'track_usr' => array( 'totalsType' => '' ),
'track_date' => array( 'totalsType' => '' ),
'tk_fecha_i' => array( 'totalsType' => '' ),
'tl_fecha_f' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'sol_id',
'sol_ticket',
'ID_FK',
'nombre',
'primer_apellido',
'segundo_apellido',
'tipo_documento',
'numero_documento',
'telefono',
'departamento',
'municipio',
'direccion',
'cargo',
'email_contacto',
'email_contacto_c',
'token_id',
'cert_id',
'vigencia',
'stage',
'doc_acta',
'doc_carta',
'doc_certificado',
'doc_poder',
'doc_rut',
'doc_cedula',
'doc_escritura',
'track_msj',
'track_usr',
'track_date',
'tk_fecha_i',
'tl_fecha_f' ),
'exportFields' => array( 'sol_id',
'ID_FK',
'nombre',
'primer_apellido',
'segundo_apellido',
'tipo_documento',
'numero_documento',
'telefono',
'departamento',
'municipio',
'direccion',
'cargo',
'email_contacto',
'email_contacto_c',
'token_id',
'cert_id',
'vigencia',
'stage',
'sol_ticket',
'doc_acta',
'doc_carta',
'doc_certificado',
'doc_poder',
'doc_rut',
'doc_cedula',
'doc_escritura',
'track_msj',
'track_usr',
'track_date',
'tk_fecha_i',
'tl_fecha_f' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'sol_id' => array( 'export_field' ),
'sol_ticket' => array( 'export_field1' ),
'ID_FK' => array( 'export_field2' ),
'nombre' => array( 'export_field3' ),
'primer_apellido' => array( 'export_field4' ),
'segundo_apellido' => array( 'export_field5' ),
'tipo_documento' => array( 'export_field6' ),
'numero_documento' => array( 'export_field7' ),
'telefono' => array( 'export_field8' ),
'departamento' => array( 'export_field9' ),
'municipio' => array( 'export_field10' ),
'direccion' => array( 'export_field11' ),
'cargo' => array( 'export_field12' ),
'email_contacto' => array( 'export_field13' ),
'email_contacto_c' => array( 'export_field14' ),
'token_id' => array( 'export_field15' ),
'cert_id' => array( 'export_field16' ),
'vigencia' => array( 'export_field17' ),
'stage' => array( 'export_field18' ),
'doc_acta' => array( 'export_field19' ),
'doc_carta' => array( 'export_field20' ),
'doc_certificado' => array( 'export_field21' ),
'doc_poder' => array( 'export_field22' ),
'doc_rut' => array( 'export_field23' ),
'doc_cedula' => array( 'export_field24' ),
'doc_escritura' => array( 'export_field25' ),
'track_msj' => array( 'export_field26' ),
'track_usr' => array( 'export_field27' ),
'track_date' => array( 'export_field28' ),
'tk_fecha_i' => array( 'export_field29' ),
'tl_fecha_f' => array( 'export_field30' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field1',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field1' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field1',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'sol_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'sol_ticket',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'ID_FK',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'nombre',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'primer_apellido',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'segundo_apellido',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'tipo_documento',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'numero_documento',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'telefono',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'departamento',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'municipio',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'direccion',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'cargo',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'email_contacto',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'email_contacto_c',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'token_id',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'cert_id',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'vigencia',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'stage',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'doc_acta',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'doc_carta',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'doc_certificado',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'doc_poder',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'doc_rut',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'doc_cedula',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'doc_escritura',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'track_msj',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'track_usr',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'track_date',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'tk_fecha_i',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'tl_fecha_f',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 13,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>