<?php
			$optionsArray = array( 'totals' => array( 'ticket_id' => array( 'totalsType' => '' ),
'ticket' => array( 'totalsType' => '' ),
'fecha_ticket' => array( 'totalsType' => '' ),
'producto' => array( 'totalsType' => '' ),
'asunto' => array( 'totalsType' => '' ),
'tipo' => array( 'totalsType' => '' ),
'estado' => array( 'totalsType' => '' ),
'prioridad' => array( 'totalsType' => '' ),
'dias' => array( 'totalsType' => '' ),
'fecha_estim_respuesta' => array( 'totalsType' => '' ),
'descripcion' => array( 'totalsType' => '' ),
'imagenes' => array( 'totalsType' => '' ),
'archivos' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'sys_user',
'ticket',
'fecha_ticket',
'producto',
'asunto',
'tipo',
'estado',
'descripcion',
'imagenes',
'archivos' ),
'exportFields' => array( 'ticket',
'fecha_ticket',
'producto',
'asunto',
'tipo',
'estado',
'descripcion',
'imagenes',
'archivos',
'sys_user' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'sys_user' => array( 'export_field' ),
'ticket' => array( 'export_field1' ),
'fecha_ticket' => array( 'export_field2' ),
'producto' => array( 'export_field3' ),
'asunto' => array( 'export_field4' ),
'tipo' => array( 'export_field5' ),
'estado' => array( 'export_field6' ),
'descripcion' => array( 'export_field10' ),
'imagenes' => array( 'export_field11' ),
'archivos' => array( 'export_field12' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field10',
'export_field11',
'export_field12',
'export_field' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field10',
'export_field11',
'export_field12' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field10',
'export_field11',
'export_field12',
'export_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'sys_user',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'ticket',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'fecha_ticket',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'producto',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'asunto',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'tipo',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'estado',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'descripcion',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'imagenes',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'archivos',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 13,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>