<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'activationField' => 'active',
'active' => true,
'code' => '00',
'codeField' => '',
'emailField' => 'email',
'extUserIdField' => '',
'fullnameField' => 'fullname',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'phoneField' => '',
'resetDateField' => 'reset_date1',
'resetTokenField' => 'reset_token1',
'table' => array( 'connId' => 'sgiysp_at_127_0_0_1',
'table' => 'camerfirma_104_users' ),
'twoFactorField' => '',
'userGroupField' => 'groupid',
'usernameField' => 'username',
'userpicField' => '' ) ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => 'UcAJkJ2YfgSHtatx6WQt',
'JWTSecret' => 'm9EXumqbLiaxDuNcNLuC' ),
'registration' => array( 'passwordValidation' => array( 'strong' => false,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => false ),
'remindMethod' => 1,
'hashAlgorithm' => 1,
'adminEmail' => 'agutierrezd@mincit.gov.co',
'caseInsensitiveLogin' => false,
'changePasswordPage' => true,
'hashPassword' => true,
'notifyAdmin' => true,
'notifyUser' => true,
'registerPage' => false,
'remindPasswordPage' => true,
'sendActivationLink' => true ),
'captchaSettings' => array( 'captchaType' => 0,
'siteKey' => '',
'secretKey' => '',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => 'sirc@mincit.gov.co',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => 'smtp.office365.com',
'SMTPPort' => 587,
'SMTPUser' => 'sirc@mincit.gov.co',
'SMTPPassword' => 'Mcit2021*',
'securityProtocol' => 2 ),
'advancedSecurity' => array( 'allowGuestLogin' => false ),
'auditAndLocking' => array( 'loggingTable' => array( 'connId' => 'sgiysp_at_127_0_0_1',
'table' => 'camerfirma_104_audit' ),
'lockingTable' => array( 'connId' => 'sgiysp_at_127_0_0_1',
'table' => 'camerfirma_104_locking' ),
'tables' => array( 'admin_members' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'admin_rights' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'admin_users' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'camerfirma_104_users' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'camerfirma_104_users_gestion' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'camerfirma_104_users_q' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'certificados_solicitud' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'certificados_solicitud_tr_0' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'certificados_solicitud_tr_1' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'certificados_solicitud_tr_2' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'certificados_solicitud_tr_3' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'certificados_solicitud_tr_4' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'certificados_solicitud_tr_5' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'certificados_solicitud_tr_6' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'certificados_solicitud_track' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'certificados_tipo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'certificados_tipo_q' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'dependencia_tipo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'dependencia_tipo_user' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'mail_messages' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_divipola' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tickets' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tickets_prioridad' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tickets_proyectos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tickets_tipo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'token_tipo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'token_tipo_q' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tp_certificados' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tp_certificados_anexos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tp_stage' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tp_stage_tk' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tp_tipodocident' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tp_token' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tp_vigencia' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ) ),
'loggingMode' => 1,
'loggingFile' => 'audit.log',
'logSecurityActions' => true,
'lockAfterUnsuccessfulLogin' => true,
'enableLocking' => true ),
'twoFactorSettings' => array( 'available' => false,
'required' => false,
'enable' => true,
'remember' => true,
'types' => array(  ),
'twoFactorField' => '',
'emailField' => '',
'phoneField' => '',
'codeField' => '',
'projectName' => '' ),
'projectName' => 'camerfirma_Ver_109',
'loginDataSource' => 'camerfirma_104_users',
'loginForm' => 1,
'dynamicPermissions' => true,
'dpTablePrefix' => 'camerfirma_104_',
'dpTableConnId' => 'sgiysp_at_127_0_0_1',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '00',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'activationField' => 'active',
'active' => true,
'code' => '00',
'codeField' => '',
'emailField' => 'email',
'extUserIdField' => '',
'fullnameField' => 'fullname',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'phoneField' => '',
'resetDateField' => 'reset_date1',
'resetTokenField' => 'reset_token1',
'table' => array( 'connId' => 'sgiysp_at_127_0_0_1',
'table' => 'camerfirma_104_users' ),
'twoFactorField' => '',
'userGroupField' => 'groupid',
'usernameField' => 'username',
'userpicField' => '' ),
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array( '00' ),
'notifications' => array(  ) );
?>